import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Common Melbourne metro suburbs for MVP launch coverage. Not exhaustive —
// consumers whose suburb isn't listed can still submit via the "my suburb
// isn't listed" fallback, which is treated as UNSERVICEABLE per
// docs/PRD.md FR-1.
const MELBOURNE_SUBURBS: Array<{ name: string; postcode: string; region: string }> = [
  { name: "Melbourne", postcode: "3000", region: "Melbourne - Inner" },
  { name: "Southbank", postcode: "3006", region: "Melbourne - Inner" },
  { name: "Docklands", postcode: "3008", region: "Melbourne - Inner" },
  { name: "Carlton", postcode: "3053", region: "Melbourne - Inner" },
  { name: "Fitzroy", postcode: "3065", region: "Melbourne - Inner" },
  { name: "Collingwood", postcode: "3066", region: "Melbourne - Inner" },
  { name: "Richmond", postcode: "3121", region: "Melbourne - Inner" },
  { name: "South Yarra", postcode: "3141", region: "Melbourne - Inner" },
  { name: "Prahran", postcode: "3181", region: "Melbourne - Inner" },
  { name: "St Kilda", postcode: "3182", region: "Melbourne - Inner South" },
  { name: "Brighton", postcode: "3186", region: "Melbourne - Inner South" },
  { name: "Elwood", postcode: "3184", region: "Melbourne - Inner South" },
  { name: "Hawthorn", postcode: "3122", region: "Melbourne - Inner East" },
  { name: "Camberwell", postcode: "3124", region: "Melbourne - Inner East" },
  { name: "Glen Waverley", postcode: "3150", region: "Melbourne - Outer East" },
  { name: "Box Hill", postcode: "3128", region: "Melbourne - Inner East" },
  { name: "Doncaster", postcode: "3108", region: "Melbourne - Outer East" },
  { name: "Ringwood", postcode: "3134", region: "Melbourne - Outer East" },
  { name: "Blackburn", postcode: "3130", region: "Melbourne - Inner East" },
  { name: "Kew", postcode: "3101", region: "Melbourne - Inner East" },
  { name: "Northcote", postcode: "3070", region: "Melbourne - Inner North" },
  { name: "Brunswick", postcode: "3056", region: "Melbourne - Inner North" },
  { name: "Coburg", postcode: "3058", region: "Melbourne - Inner North" },
  { name: "Preston", postcode: "3072", region: "Melbourne - Inner North" },
  { name: "Reservoir", postcode: "3073", region: "Melbourne - Outer North" },
  { name: "Essendon", postcode: "3040", region: "Melbourne - Inner West" },
  { name: "Footscray", postcode: "3011", region: "Melbourne - Inner West" },
  { name: "Yarraville", postcode: "3013", region: "Melbourne - Inner West" },
  { name: "Williamstown", postcode: "3016", region: "Melbourne - Inner West" },
  { name: "Sunshine", postcode: "3020", region: "Melbourne - Outer West" },
  { name: "Werribee", postcode: "3030", region: "Melbourne - Outer West" },
  { name: "Point Cook", postcode: "3030", region: "Melbourne - Outer West" },
  { name: "Caroline Springs", postcode: "3023", region: "Melbourne - Outer West" },
  { name: "Dandenong", postcode: "3175", region: "Melbourne - Outer South East" },
  { name: "Frankston", postcode: "3199", region: "Melbourne - Outer South East" },
  { name: "Cranbourne", postcode: "3977", region: "Melbourne - Outer South East" },
  { name: "Pakenham", postcode: "3810", region: "Melbourne - Outer South East" },
  { name: "Mornington", postcode: "3931", region: "Melbourne - Mornington Peninsula" },
  { name: "Berwick", postcode: "3806", region: "Melbourne - Outer South East" },
  { name: "Bundoora", postcode: "3083", region: "Melbourne - Outer North" },
  { name: "Epping", postcode: "3076", region: "Melbourne - Outer North" },

  // Inner
  { name: "East Melbourne", postcode: "3002", region: "Melbourne - Inner" },
  { name: "North Melbourne", postcode: "3051", region: "Melbourne - Inner" },
  { name: "West Melbourne", postcode: "3003", region: "Melbourne - Inner" },
  { name: "Kensington", postcode: "3031", region: "Melbourne - Inner" },
  { name: "Flemington", postcode: "3031", region: "Melbourne - Inner" },
  { name: "Parkville", postcode: "3052", region: "Melbourne - Inner" },
  { name: "Carlton North", postcode: "3054", region: "Melbourne - Inner" },
  { name: "Fitzroy North", postcode: "3068", region: "Melbourne - Inner North" },
  { name: "Abbotsford", postcode: "3067", region: "Melbourne - Inner" },
  { name: "Cremorne", postcode: "3121", region: "Melbourne - Inner" },
  { name: "Windsor", postcode: "3181", region: "Melbourne - Inner" },
  { name: "South Melbourne", postcode: "3205", region: "Melbourne - Inner South" },
  { name: "Albert Park", postcode: "3206", region: "Melbourne - Inner South" },
  { name: "Middle Park", postcode: "3206", region: "Melbourne - Inner South" },
  { name: "Port Melbourne", postcode: "3207", region: "Melbourne - Inner South" },

  // Inner South
  { name: "St Kilda East", postcode: "3183", region: "Melbourne - Inner South" },
  { name: "Balaclava", postcode: "3183", region: "Melbourne - Inner South" },
  { name: "Ripponlea", postcode: "3185", region: "Melbourne - Inner South" },
  { name: "Elsternwick", postcode: "3185", region: "Melbourne - Inner South" },
  { name: "Brighton East", postcode: "3187", region: "Melbourne - Inner South" },
  { name: "Hampton", postcode: "3188", region: "Melbourne - Inner South" },
  { name: "Sandringham", postcode: "3191", region: "Melbourne - Inner South" },
  { name: "Black Rock", postcode: "3193", region: "Melbourne - Inner South" },
  { name: "Beaumaris", postcode: "3193", region: "Melbourne - Inner South" },
  { name: "Cheltenham", postcode: "3192", region: "Melbourne - Inner South" },
  { name: "Mentone", postcode: "3194", region: "Melbourne - Inner South" },
  { name: "Mordialloc", postcode: "3195", region: "Melbourne - Inner South" },
  { name: "Aspendale", postcode: "3195", region: "Melbourne - Inner South" },
  { name: "Chelsea", postcode: "3196", region: "Melbourne - Inner South" },
  { name: "Bentleigh", postcode: "3204", region: "Melbourne - Inner South" },
  { name: "Bentleigh East", postcode: "3165", region: "Melbourne - Inner South" },
  { name: "Ormond", postcode: "3204", region: "Melbourne - Inner South" },
  { name: "McKinnon", postcode: "3204", region: "Melbourne - Inner South" },
  { name: "Caulfield", postcode: "3162", region: "Melbourne - Inner South" },
  { name: "Caulfield North", postcode: "3161", region: "Melbourne - Inner South" },
  { name: "Caulfield South", postcode: "3162", region: "Melbourne - Inner South" },
  { name: "Malvern", postcode: "3144", region: "Melbourne - Inner South" },
  { name: "Malvern East", postcode: "3145", region: "Melbourne - Inner South" },
  { name: "Armadale", postcode: "3143", region: "Melbourne - Inner South" },
  { name: "Toorak", postcode: "3142", region: "Melbourne - Inner South" },
  { name: "Glen Iris", postcode: "3146", region: "Melbourne - Inner South" },

  // Inner East
  { name: "Hawthorn East", postcode: "3123", region: "Melbourne - Inner East" },
  { name: "Canterbury", postcode: "3126", region: "Melbourne - Inner East" },
  { name: "Kew East", postcode: "3102", region: "Melbourne - Inner East" },
  { name: "Balwyn", postcode: "3103", region: "Melbourne - Inner East" },
  { name: "Balwyn North", postcode: "3104", region: "Melbourne - Inner East" },
  { name: "Box Hill North", postcode: "3129", region: "Melbourne - Inner East" },
  { name: "Box Hill South", postcode: "3128", region: "Melbourne - Inner East" },
  { name: "Blackburn North", postcode: "3130", region: "Melbourne - Inner East" },
  { name: "Blackburn South", postcode: "3130", region: "Melbourne - Inner East" },
  { name: "Surrey Hills", postcode: "3127", region: "Melbourne - Inner East" },
  { name: "Mont Albert", postcode: "3127", region: "Melbourne - Inner East" },

  // Outer East
  { name: "Doncaster East", postcode: "3109", region: "Melbourne - Outer East" },
  { name: "Templestowe", postcode: "3106", region: "Melbourne - Outer East" },
  { name: "Templestowe Lower", postcode: "3107", region: "Melbourne - Outer East" },
  { name: "Bulleen", postcode: "3105", region: "Melbourne - Outer East" },
  { name: "Ringwood East", postcode: "3135", region: "Melbourne - Outer East" },
  { name: "Ringwood North", postcode: "3134", region: "Melbourne - Outer East" },
  { name: "Croydon", postcode: "3136", region: "Melbourne - Outer East" },
  { name: "Mooroolbark", postcode: "3138", region: "Melbourne - Outer East" },
  { name: "Lilydale", postcode: "3140", region: "Melbourne - Outer East" },
  { name: "Mount Evelyn", postcode: "3796", region: "Melbourne - Outer East" },
  { name: "Wheelers Hill", postcode: "3150", region: "Melbourne - Outer East" },
  { name: "Mulgrave", postcode: "3170", region: "Melbourne - Outer East" },
  { name: "Vermont", postcode: "3133", region: "Melbourne - Outer East" },
  { name: "Vermont South", postcode: "3133", region: "Melbourne - Outer East" },
  { name: "Mitcham", postcode: "3132", region: "Melbourne - Outer East" },
  { name: "Nunawading", postcode: "3131", region: "Melbourne - Outer East" },
  { name: "Forest Hill", postcode: "3131", region: "Melbourne - Outer East" },
  { name: "Knoxfield", postcode: "3180", region: "Melbourne - Outer East" },
  { name: "Wantirna", postcode: "3152", region: "Melbourne - Outer East" },
  { name: "Wantirna South", postcode: "3152", region: "Melbourne - Outer East" },
  { name: "Bayswater", postcode: "3153", region: "Melbourne - Outer East" },
  { name: "Boronia", postcode: "3155", region: "Melbourne - Outer East" },
  { name: "Ferntree Gully", postcode: "3156", region: "Melbourne - Outer East" },
  { name: "Upwey", postcode: "3158", region: "Melbourne - Outer East" },
  { name: "Belgrave", postcode: "3160", region: "Melbourne - Outer East" },
  { name: "Rowville", postcode: "3178", region: "Melbourne - Outer East" },

  // Inner North
  { name: "Thornbury", postcode: "3071", region: "Melbourne - Inner North" },
  { name: "Brunswick East", postcode: "3057", region: "Melbourne - Inner North" },
  { name: "Brunswick West", postcode: "3055", region: "Melbourne - Inner North" },
  { name: "Coburg North", postcode: "3058", region: "Melbourne - Inner North" },
  { name: "Fawkner", postcode: "3060", region: "Melbourne - Inner North" },
  { name: "Pascoe Vale", postcode: "3044", region: "Melbourne - Inner North" },
  { name: "Pascoe Vale South", postcode: "3044", region: "Melbourne - Inner North" },
  { name: "Moonee Ponds", postcode: "3039", region: "Melbourne - Inner North" },
  { name: "Ascot Vale", postcode: "3032", region: "Melbourne - Inner North" },
  { name: "Travancore", postcode: "3032", region: "Melbourne - Inner North" },

  // Outer North
  { name: "Thomastown", postcode: "3074", region: "Melbourne - Outer North" },
  { name: "Lalor", postcode: "3075", region: "Melbourne - Outer North" },
  { name: "Mill Park", postcode: "3082", region: "Melbourne - Outer North" },
  { name: "South Morang", postcode: "3752", region: "Melbourne - Outer North" },
  { name: "Mernda", postcode: "3754", region: "Melbourne - Outer North" },
  { name: "Doreen", postcode: "3754", region: "Melbourne - Outer North" },
  { name: "Whittlesea", postcode: "3757", region: "Melbourne - Outer North" },
  { name: "Craigieburn", postcode: "3064", region: "Melbourne - Outer North" },
  { name: "Roxburgh Park", postcode: "3064", region: "Melbourne - Outer North" },
  { name: "Broadmeadows", postcode: "3047", region: "Melbourne - Outer North" },
  { name: "Meadow Heights", postcode: "3048", region: "Melbourne - Outer North" },
  { name: "Coolaroo", postcode: "3048", region: "Melbourne - Outer North" },
  { name: "Greenvale", postcode: "3059", region: "Melbourne - Outer North" },
  { name: "Gladstone Park", postcode: "3043", region: "Melbourne - Outer North" },
  { name: "Tullamarine", postcode: "3043", region: "Melbourne - Outer North" },
  { name: "Airport West", postcode: "3042", region: "Melbourne - Outer North" },
  { name: "Keilor", postcode: "3036", region: "Melbourne - Outer North" },
  { name: "Keilor East", postcode: "3033", region: "Melbourne - Outer North" },
  { name: "Keilor Downs", postcode: "3038", region: "Melbourne - Outer North" },
  { name: "St Albans", postcode: "3021", region: "Melbourne - Outer North" },
  { name: "Sunbury", postcode: "3429", region: "Melbourne - Outer North" },
  { name: "Diggers Rest", postcode: "3427", region: "Melbourne - Outer North" },

  // Inner West
  { name: "Essendon North", postcode: "3041", region: "Melbourne - Inner West" },
  { name: "Aberfeldie", postcode: "3040", region: "Melbourne - Inner West" },
  { name: "West Footscray", postcode: "3012", region: "Melbourne - Inner West" },
  { name: "Seddon", postcode: "3011", region: "Melbourne - Inner West" },
  { name: "Kingsville", postcode: "3012", region: "Melbourne - Inner West" },
  { name: "Maidstone", postcode: "3012", region: "Melbourne - Inner West" },
  { name: "Braybrook", postcode: "3019", region: "Melbourne - Inner West" },
  { name: "Williamstown North", postcode: "3016", region: "Melbourne - Inner West" },
  { name: "Newport", postcode: "3015", region: "Melbourne - Inner West" },
  { name: "Spotswood", postcode: "3015", region: "Melbourne - Inner West" },
  { name: "Altona", postcode: "3018", region: "Melbourne - Inner West" },
  { name: "Altona North", postcode: "3025", region: "Melbourne - Inner West" },
  { name: "Altona Meadows", postcode: "3028", region: "Melbourne - Outer West" },
  { name: "Laverton", postcode: "3028", region: "Melbourne - Outer West" },
  { name: "Seabrook", postcode: "3028", region: "Melbourne - Outer West" },

  // Outer West
  { name: "Sunshine North", postcode: "3020", region: "Melbourne - Outer West" },
  { name: "Sunshine West", postcode: "3020", region: "Melbourne - Outer West" },
  { name: "Albion", postcode: "3020", region: "Melbourne - Outer West" },
  { name: "Ardeer", postcode: "3022", region: "Melbourne - Outer West" },
  { name: "Deer Park", postcode: "3023", region: "Melbourne - Outer West" },
  { name: "Burnside", postcode: "3023", region: "Melbourne - Outer West" },
  { name: "Cairnlea", postcode: "3023", region: "Melbourne - Outer West" },
  { name: "Taylors Lakes", postcode: "3038", region: "Melbourne - Outer West" },
  { name: "Hillside", postcode: "3037", region: "Melbourne - Outer West" },
  { name: "Sydenham", postcode: "3037", region: "Melbourne - Outer West" },
  { name: "Delahey", postcode: "3037", region: "Melbourne - Outer West" },
  { name: "Kealba", postcode: "3021", region: "Melbourne - Outer West" },
  { name: "Melton", postcode: "3337", region: "Melbourne - Outer West" },
  { name: "Melton South", postcode: "3338", region: "Melbourne - Outer West" },
  { name: "Hoppers Crossing", postcode: "3029", region: "Melbourne - Outer West" },
  { name: "Tarneit", postcode: "3029", region: "Melbourne - Outer West" },
  { name: "Truganina", postcode: "3029", region: "Melbourne - Outer West" },
  { name: "Wyndham Vale", postcode: "3024", region: "Melbourne - Outer West" },
  { name: "Manor Lakes", postcode: "3024", region: "Melbourne - Outer West" },
  { name: "Little River", postcode: "3211", region: "Melbourne - Outer West" },

  // Outer South East
  { name: "Dandenong North", postcode: "3175", region: "Melbourne - Outer South East" },
  { name: "Noble Park", postcode: "3174", region: "Melbourne - Outer South East" },
  { name: "Springvale", postcode: "3171", region: "Melbourne - Outer South East" },
  { name: "Springvale South", postcode: "3172", region: "Melbourne - Outer South East" },
  { name: "Keysborough", postcode: "3173", region: "Melbourne - Outer South East" },
  { name: "Clayton", postcode: "3168", region: "Melbourne - Outer South East" },
  { name: "Clayton South", postcode: "3169", region: "Melbourne - Outer South East" },
  { name: "Oakleigh", postcode: "3166", region: "Melbourne - Outer South East" },
  { name: "Oakleigh East", postcode: "3166", region: "Melbourne - Outer South East" },
  { name: "Huntingdale", postcode: "3166", region: "Melbourne - Outer South East" },
  { name: "Mount Waverley", postcode: "3149", region: "Melbourne - Outer East" },
  { name: "Chadstone", postcode: "3148", region: "Melbourne - Outer South East" },
  { name: "Hughesdale", postcode: "3166", region: "Melbourne - Outer South East" },
  { name: "Murrumbeena", postcode: "3163", region: "Melbourne - Outer South East" },
  { name: "Carnegie", postcode: "3163", region: "Melbourne - Inner South" },
  { name: "Clarinda", postcode: "3169", region: "Melbourne - Outer South East" },
  { name: "Narre Warren", postcode: "3805", region: "Melbourne - Outer South East" },
  { name: "Narre Warren South", postcode: "3805", region: "Melbourne - Outer South East" },
  { name: "Hallam", postcode: "3803", region: "Melbourne - Outer South East" },
  { name: "Endeavour Hills", postcode: "3802", region: "Melbourne - Outer South East" },
  { name: "Hampton Park", postcode: "3976", region: "Melbourne - Outer South East" },
  { name: "Cranbourne North", postcode: "3977", region: "Melbourne - Outer South East" },
  { name: "Cranbourne East", postcode: "3977", region: "Melbourne - Outer South East" },
  { name: "Clyde", postcode: "3978", region: "Melbourne - Outer South East" },
  { name: "Clyde North", postcode: "3978", region: "Melbourne - Outer South East" },
  { name: "Officer", postcode: "3809", region: "Melbourne - Outer South East" },
  { name: "Beaconsfield", postcode: "3807", region: "Melbourne - Outer South East" },

  // Mornington Peninsula
  { name: "Frankston South", postcode: "3199", region: "Melbourne - Mornington Peninsula" },
  { name: "Carrum Downs", postcode: "3201", region: "Melbourne - Mornington Peninsula" },
  { name: "Seaford", postcode: "3198", region: "Melbourne - Mornington Peninsula" },
  { name: "Langwarrin", postcode: "3910", region: "Melbourne - Mornington Peninsula" },
  { name: "Mount Eliza", postcode: "3930", region: "Melbourne - Mornington Peninsula" },
  { name: "Mount Martha", postcode: "3934", region: "Melbourne - Mornington Peninsula" },
  { name: "Hastings", postcode: "3915", region: "Melbourne - Mornington Peninsula" },
  { name: "Rosebud", postcode: "3939", region: "Melbourne - Mornington Peninsula" },
  { name: "Rye", postcode: "3941", region: "Melbourne - Mornington Peninsula" },
  { name: "Sorrento", postcode: "3943", region: "Melbourne - Mornington Peninsula" },
  { name: "Portsea", postcode: "3944", region: "Melbourne - Mornington Peninsula" },
  { name: "Dromana", postcode: "3936", region: "Melbourne - Mornington Peninsula" },
  { name: "Somerville", postcode: "3912", region: "Melbourne - Mornington Peninsula" },
  { name: "Baxter", postcode: "3911", region: "Melbourne - Mornington Peninsula" },
];

async function main() {
  for (const suburb of MELBOURNE_SUBURBS) {
    const existing = await prisma.suburb.findFirst({
      where: { name: suburb.name, postcode: suburb.postcode, state: "VIC" },
    });

    if (existing) {
      console.log(`${suburb.name} ${suburb.postcode} already exists — skipping`);
      continue;
    }

    await prisma.suburb.create({
      data: {
        name: suburb.name,
        postcode: suburb.postcode,
        state: "VIC",
        region: suburb.region,
      },
    });

    console.log(`Created suburb: ${suburb.name} ${suburb.postcode}`);
  }
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
